### ISSUE TITLE
Update button styles

### ISSUE THREAD

**Issue by donnapep** [Automattic/course#13]
Update the button styles for the various states as per the [design](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020042%3A329). Example PRs [here](https://github.com/Automattic/themes/pull/6498) and [here](https://github.com/Automattic/themes/pull/6567).

Note that _Main_ is the _Fill_ style and _Secondary_ is the _Outline_ style:

![Screen Shot 2022-10-05 at 8 33 53 AM](https://user-images.githubusercontent.com/1190420/194061281-fee9cd7a-627b-4f7e-acbe-ca7c9a51fd3e.jpg)

#### Scenario: Button styles
**Given** I've added Fill and Outline buttons to a page
**When** I view that page on the frontend
**Then** the button styles update as per the design for each state.

**Comment by Luchadores** [comment]
For button states, the same review I've made [here](https://lavagolemnotes.wordpress.com/2022/10/14/call-for-validating/#comment-3) applies.

---
Size
The height doesn’t match the one we have in the design.

**General**

Design Button Height: 56px
Margin/Padding from text to left and right: 32px
Font size: 21px

**Styles**
- We're missing the border styles.
- No underline on the text of the button at hover.
