### ISSUE TITLE
Update styling of site title in footer

### ISSUE THREAD

**Issue by donnapep** [Automattic/course#132]
The site title is no longer resizing properly in the footer. Let's get rid of the auto-sizing, left align the site title, use normal paragraph text (i.e. not a heading), and a large font size.

Discussion can be found [here](https://senseip2.wordpress.com/2022/12/02/call-for-testing-learning-mode-updates-new-patterns/#comment-5321).

**Comment by gabrielcaires** [comment]
Blocked by :
Waiting for feedback on a solution https://github.com/Automattic/course/pull/134 that could close this issue
