### ISSUE TITLE
Remove whitespace between testimonial and footer for landing page patterns

### ISSUE THREAD

**Issue by donnapep** [Automattic/course#141]
For both of the Landing Page patterns, there is whitespace between the bottom edge of the testimonial and the footer. There shouldn't be any whitespace here as per the [design](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020052%3A2426&t=kgMDJYcUMSKxJYG4-0).

Note that this whitespace should only be removed from these patterns. We still want it on other templates.

![Screenshot 2022-12-02 at 11 23 30 AM](https://user-images.githubusercontent.com/1190420/205338636-91253ea2-129d-43be-923c-ab72dcbf1191.jpg)

**Comment by gabrielcaires** [comment]
Fixed here https://github.com/Automattic/course/issues/141
