### ISSUE TITLE
Empty Course List block in lesson breaks the page

### ISSUE THREAD

**Issue by StefMattana** [Automattic/course#151]
I accidentally added a Course List block in a test lesson page and left it blank. 

<img width="1194" alt="Screenshot 2022-12-06 at 14 02 24" src="https://user-images.githubusercontent.com/11662998/205932594-ed14e594-8bc1-4101-ac2d-787311e5d079.png">

Once published, the page displayed lots of errors which didn't even fit the template I chose for the lesson: 

<img width="1896" alt="Screenshot 2022-12-06 at 14 03 51" src="https://user-images.githubusercontent.com/11662998/205932897-fde2ef8b-913d-499e-abd3-82f3b2796d76.png">

Populating the block resulted in no errors on the front end, and the content displayed as expected. 

This is minor, but I wonder if it'd be possible to give users an alert when there's an empty block in the page right before publishing it.

**Comment by mikeyarce** [comment]
Good find, @StefMattana !  This seems to be more of an issue with the Course List Block and not with the theme, so I've opened up this issue https://github.com/Automattic/sensei/issues/6238 and will close this one.
