### ISSUE TITLE
Lesson Learning Mode (Default template) makes lesson's publishing impossible

### ISSUE THREAD

**Issue by StefMattana** [Automattic/course#152]
On my test lesson editor, I can see two template options: 

- Default
- Lesson Learning Mode (Default template)

The Default template also displays as `Lesson (Learning...` upon selecting it: 

<img width="436" alt="Screenshot 2022-12-06 at 14 26 52" src="https://user-images.githubusercontent.com/11662998/205938216-c319696e-c4d4-445f-93c2-52bce167c76e.png">

I got confused by the wording as I expected the Default template to display as `Default`, not exactly like the other template option. 

I then switched the template to the `Lesson Learning Mode (Default template)` option. 
<img width="360" alt="Screenshot 2022-12-06 at 14 28 36" src="https://user-images.githubusercontent.com/11662998/205938685-e375fa90-4b81-437f-9a59-4381a61b7d78.png">

When publishing the lesson, I got the following error: 
<img width="2026" alt="Screenshot 2022-12-06 at 14 29 35" src="https://user-images.githubusercontent.com/11662998/205938947-8311525c-b9e9-4018-bb82-740d0345fce4.png">

The Inspector Console reports `Failed to load resource: the server responded with a status of 400 ()` `on /wp-json/wp/v2/lessons/24?_locale=user:1` 

I had to select the Default template to publish my lesson, so the `Lesson Learning Mode (Default template)` option in the dropdown menu doesn't work on my end.

**Comment by mikeyarce** [comment]
Tested this out and I see that this happens even without the Course theme active, so I've moved it to the Sensei repo here: https://github.com/Automattic/sensei/issues/6276
