### ISSUE TITLE
Contact Teacher button is not visible

### ISSUE THREAD

**Issue by donnapep** [Automattic/course#155]
I'm not sure why, but we're [hiding the _Contact Teacher_ block](https://github.com/Automattic/course/blob/trunk/learning-mode.css#L208), making it impossible for students to send messages to the teacher.

Presumably, this was only supposed to hide the block in Learning Mode since the change is in `learning-mode.css`, but the block is visible in Learning Mode on other themes. I don't see any compelling reason for why we'd ever want to hide this block, so can only assume it was an oversight.

**Comment by renatho** [comment]
I noticed it being hidden on the Course page either, even without Learning Mode enabled.

**Comment by donnapep** [comment]
p1668438008975119-slack-C029FM1EH
