### ISSUE TITLE
Update theme colors

### ISSUE THREAD

**Issue by donnapep** [Automattic/course#2]
Update the theme colors to match the [design](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020042%3A442). See [this PR](https://github.com/Automattic/themes/pull/6478) as an example.

![Screen Shot 2022-09-27 at 1 19 34 PM](https://user-images.githubusercontent.com/1190420/192593872-068aa58e-c8c8-4d1c-a61e-a68528e61c47.jpg)

#### Scenario: Theme colors in the editor
**Given** I'm adding a paragraph block to a page
**When** I click on the paragraph's text or background color settings
**Then** I should see the custom color palette displayed below the _Theme_ heading.

#### Scenario: Theme colors on the frontend
**Given** The Course theme is activated
**When** I view the frontend of the site
**Then** I should see the theme colors being applied.

**Comment by Luchadores** [comment]
Hello 👋 
The same comment I left [here](https://lavagolemnotes.wordpress.com/2022/10/14/call-for-validating/#comment-2) last week, applies here again. 

---
The Main & Secondary colors don’t match the design. Below are the Hex values from Figma to help you update it.

Main Design Hex: #00594F
Secondary Design Hex: #F7EFAD

Code on the left side, Design on the right side.

![image](https://user-images.githubusercontent.com/10038976/197749672-4d115193-cc12-447f-8699-45a71ac52e5c.png)
