### ISSUE TITLE
Update typography settings

### ISSUE THREAD

**Issue by donnapep** [Automattic/course#3]
Update the typography settings so that they match the [desktop](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020042%3A412) and [mobile](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020042%3A427) designs. Example PRs [here](https://github.com/Automattic/themes/pull/6479), [here](https://github.com/Automattic/themes/pull/6487) and [here](https://github.com/Automattic/themes/pull/6571).

## Desktop
![Screen Shot 2022-09-30 at 3 12 13 PM](https://user-images.githubusercontent.com/1190420/193340595-617411da-7914-4c08-abaf-8e645ea814bf.jpg)

## Mobile
![Screen Shot 2022-09-30 at 3 12 40 PM](https://user-images.githubusercontent.com/1190420/193340649-50b5fe1b-4a03-42a1-bd1b-4b4059b939ca.jpg)

#### Scenario: Typography settings
**Given** The Sensei theme is activated
**When** I view a page containing `h1` - `h4` headings and paragraph blocks
**Then** the typography looks similar to the design on both desktop and mobile.

**Comment by Luchadores** [comment]
The typography looks nice. 
I haven't noticed any changes from the last time I checked it. So I would refer to my comment [here](https://lavagolemnotes.wordpress.com/2022/10/14/call-for-validating/#comment-4).

What I would check is the line-height for the paragraphs. 

- size: 24px
- line-height: 130%

I would also check the line-height for headers, in case users want to use them for more text and they would end up having line breaks.

![image](https://user-images.githubusercontent.com/10038976/197754746-018be5eb-cfda-42cf-90f9-cb7c9d552809.png)
