### ISSUE TITLE
Update link styles

### ISSUE THREAD

**Issue by donnapep** [Automattic/course#4]
Update the link styles for the various states as per the [design](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020042%3A329). Example PRs [here](https://github.com/Automattic/themes/pull/6517) and [here](https://github.com/Automattic/themes/pull/6570).

In the screenshot below, the columns are, in order:
- Default state
- Hover state
- Click state
- Focus state
- Active state

![Screen Shot 2022-10-05 at 9 36 27 AM](https://user-images.githubusercontent.com/1190420/194073911-0ba1bb2c-3534-4f03-9fb2-f35775b5e086.jpg)

#### Scenario: Link styles
**Given** I've added a link in a paragraph block on a page
**When** I view the page on the frontend
**Then** the link style updates as per the design for each state.

**Comment by Luchadores** [comment]
This works great in my testing. Thank you 🎉
