### ISSUE TITLE
Learning Mode - Style tweaks for all Learning Mode templates

### ISSUE THREAD

**Issue by donnapep** [Automattic/course#46]
Update the Learning Mode templates so that they match the [design](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020082%3A4588). Note that there's a [separate issue](https://github.com/Automattic/sensei-theme/issues/47) to make more style tweaks to individual templates. As part of this, the theme will need to opt out of opinionated Learning Mode styles so that theme styles are applied instead.

Following are the common elements that need to be updated across all templates. It's possible that not all of these UI elements will be able to be targeted in `theme.json`. The sidebar in particular was mentioned as something that may be tricky to customize.

Also, once https://github.com/Automattic/sensei-theme/issues/48 is implemented, some of these styling tweaks may no longer be necessary.

## Header
_Course title_ - Font family, font weight, font size, uppercase
_Exit course link_ - Font family, font size, underline

## Sidebar (Course Outline)
_Module title_ - Uppercase, font family, font weight, font size
_Completed status indicator (checkmark)_ - No fill, green checkmark
_Lesson title_ - Font family, font weight, font size
_Quiz label_ - Font family, font size
_Collapsed lesson content_ - Uppercase, font family, font size

## Buttons
Font family, font weight, font size, border radius, uppercase

---
_Note that any inconsistencies you may notice in the screenshots that are not already documented above are likely a result of designs that have not been updated since the learning mode template project was completed._

## Default Template
![Screen Shot 2022-10-20 at 9 47 37 AM](https://user-images.githubusercontent.com/1190420/196966474-f331ffb6-2638-4872-b109-e138d09c6986.jpg)

## Modern Template
![Screen Shot 2022-10-20 at 9 48 26 AM](https://user-images.githubusercontent.com/1190420/196966656-3617b2ac-2966-4633-ad54-5ab047e29a59.jpg)

### Video
![Screen Shot 2022-10-20 at 9 49 12 AM](https://user-images.githubusercontent.com/1190420/196966843-17541eb3-2f95-40af-a4af-ccb0c41e390c.jpg)

### No Video
![Screen Shot 2022-10-20 at 10 14 27 AM](https://user-images.githubusercontent.com/1190420/196973288-05ba633a-1035-48b6-86c6-146124e936d1.jpg)

## Large Video Template
![Screen Shot 2022-10-20 at 9 50 25 AM](https://user-images.githubusercontent.com/1190420/196967164-71b2c5d1-fdb0-4d23-b0bb-9f21de0b1384.jpg)

#### Scenario: Default template
**Given** The Sensei theme is activated
**And** Learning Mode is enabled for all courses
**And** the Default Learning Mode template is activated
**When** I view a lesson
**Then** the page looks similar to the Default Template screenshot.

#### Scenario: Modern template
**Given** The Sensei theme is activated
**And** Learning Mode is enabled for all courses
**And** the Modern Learning Mode template is activated
**When** I view a lesson
**Then** the page looks similar to the Modern Template screenshot.

#### Scenario: Video template
**Given** The Sensei theme is activated
**And** Learning Mode is enabled for all courses
**And** the Video Learning Mode template is activated
**When** I add the Featured Video block to a lesson
**And** I view that lesson on the frontend
**Then** the page looks similar to the Video Template - Video screenshot.

#### Scenario: Video template
**Given** The Sensei theme is activated
**And** Learning Mode is enabled for all courses
**And** the Video Learning Mode template is activated
**When** I view a lesson that doesn't contain the Featured Video block
**Then** the page looks similar to the Video Template - No Video screenshot.

#### Scenario: Large Video template
**Given** The Sensei theme is activated
**And** Learning Mode is enabled for all courses
**And** the Large Video Learning Mode template is activated
**When** I add the Featured Video block to a lesson
**And** I view that lesson on the frontend
**Then** the page looks similar to the Large Video Template screenshot.

**Comment by gabrielcaires** [comment]
The overall strategy to implement it is:

* [ ] Disable the CSS styles that are overriding the  styles from the theme.json https://github.com/Automattic/sensei/pull/6066  [Theme](https://github.com/Automattic/sensei/issues?q=is%3Apr+is%3Aopen+label%3ATheme)
* [ ]  Upgrade the Learning Mode blocks to able be customized by the theme.json [https://github.com/Automattic/sensei/pull/6067  [Theme](https://github.com/Automattic/sensei/issues?q=is%3Apr+is%3Aopen+label%3ATheme)]
* [ ]  Enable to customize some learning mode templates via CSS variables https://github.com/Automattic/sensei/pull/6068  [Theme](https://github.com/Automattic/sensei/issues?q=is%3Apr+is%3Aopen+label%3ATheme)
* [ ] Enable to customize the lesson status icons   https://github.com/Automattic/sensei/pull/6070  [Theme](https://github.com/Automattic/sensei/issues?q=is%3Apr+is%3Aopen+label%3ATheme)


After merging all of these PRs, the PR  https://github.com/Automattic/sensei-theme/pull/68 can be tested.
This one is not fully ready, so probably it requires more small tweaks, but by merging the other ones probably the main changes can be reachable via theme.json or CSS variables.
