### ISSUE TITLE
Learning Mode - Opt out of opinionated Learning Mode styles

### ISSUE THREAD

**Issue by donnapep** [Automattic/course#48]
Dependent on https://github.com/Automattic/sensei/issues/5983.

Opt out of opinionated Learning Mode styles so that theme styles are applied instead.

#### Scenario: Learning Mode
**Given** The Sensei theme is activated
**And** Learning Mode is enabled for all courses
**When** I view lessons and quizzes in a course
**Then** the theme's styles are used for the header, sidebar and buttons (i.e. these elements aren't styled by Sensei LMS).

**Comment by gabrielcaires** [comment]
@donnapep I think this card is more like an implementation detail of #46 , so we I think we can close it.

**Comment by donnapep** [comment]
Closing as per the above comment.
