### ISSUE TITLE
Update theme layout

### ISSUE THREAD

**Issue by donnapep** [Automattic/course#5]
Ensure the following layout options are similar to the [design](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020049%3A554). For body spacing and block gap, we'll need to look at the designs and set suitable values. While content wide width can be set in pixels, body spacing and block gap should use relative units (see PRs below for examples):

- `wideSize` (the width of wide blocks; we could leave this at the default value if a value is difficult to discern from the designs)
- Body spacing
  - `blockGap`
  - `padding`

Example PRs are [here](https://github.com/Automattic/themes/pull/6574) and [here](https://github.com/Automattic/themes/pull/6494).

For context, these are the sections that need updating in `theme.json`:

<img width="562" alt="image (4)" src="https://user-images.githubusercontent.com/1190420/193343596-54c00f42-1ae4-4c20-aa56-4d94b4dbbe3d.png">

<img width="946" alt="image (5)" src="https://user-images.githubusercontent.com/1190420/193343645-066e85ef-cdb5-4d54-8721-a9dca621f37b.png">

#### Scenario: Layout & Spacing
**Given** I've added multiple blocks to a page
**When** I view the page in the editor or frontend
**Then** the amount of padding between the edges of the browser and the content is sufficient on both desktop and mobile
**And** the amount of padding between blocks is sufficient on both desktop and mobile.

**Comment by Luchadores** [comment]
Hey, hey 👋 I don't really understand what to look for here. I'm not sure what the space from the edge to the content means.

Some things I noticed, which I'm not sure are related to this issue are:

- Covers do not span the full width of the page, which is what I expected.
- When adding a cover block, seems quite narrow. I do understand it grows in height if I add more content to it, but not sure that is the default behavior. I expected a Cover to take more space on height when added.
- Spacing in-between blocks, inside the editor, is set to 0, I assume? All the blocks come really close together.

Here are two images to help with what I'm describing above.
![image](https://user-images.githubusercontent.com/10038976/197758825-5144a489-749f-463c-8402-fdeded322af5.png)

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/10038976/197758338-b617846a-bdef-460b-8290-fb46def84cf7.png">

The same comments apply to mobile as well
![image](https://user-images.githubusercontent.com/10038976/197759397-d995ab33-9afe-44f5-97ee-6cbb44f9e3b3.png)

**Comment by donnapep** [comment]
@Luchadores 

> Spacing in-between blocks, inside the editor, is set to 0, I assume? All the blocks come really close together.

I'm not able to reproduce that one. We have `blockGap` (the vertical spacing between blocks) set to `2.5rem` or `40px`. A link to a page could help here, if you have one.

For the cover block, I created https://github.com/Automattic/sensei-theme/issues/56.

**Comment by Luchadores** [comment]
Hey @donnapep 👋 Might be a Jurassic Ninja site problem? Not sure. Here's the link to the page I have:
https://dusty-winter.jurassic.ninja/wp-admin/post.php?post=17&action=edit
