### ISSUE TITLE
Update theme navigation

### ISSUE THREAD

**Issue by donnapep** [Automattic/course#7]
Update the navigation so that it matches the [desktop](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020052%3A1851) and [mobile](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020116%3A2599) designs. The header should be sticky as the user scrolls. Example PRs [here](https://github.com/Automattic/themes/pull/6509) and [here](https://github.com/Automattic/themes/pull/6586).

## Considerations
- We're likely going to need to use custom CSS for this task.
- @pbking thinks we'll need to create a new block style for the _Start Here_ button.

## Desktop
Note that _Cours_ in the screenshot below is the site title and the other items (with the exception of the button) are the pages that exist on the site:

![Screen Shot 2022-09-30 at 4 30 31 PM](https://user-images.githubusercontent.com/1190420/193351632-345ba6bc-d6d6-4b84-8edd-b34b4be17c86.jpg)

### Collapsed
![Screen Shot 2022-09-30 at 4 31 42 PM](https://user-images.githubusercontent.com/1190420/193351784-613090dd-badd-4ffd-8803-5f6cb7e4ea42.jpg)

### Expanded
![Screen Shot 2022-09-30 at 4 40 40 PM](https://user-images.githubusercontent.com/1190420/193352978-63ed8c13-5c3f-4a51-9744-df78f30dbbc3.jpg)

#### Scenario: Desktop Navigation
**Given** the Sensei theme is activated
**And** I have published a blog post
**When** I view the blog post on the desktop
**Then** the navigation looks similar to the design
**And** clicking on a page navigates to that page
**And** clicking on the site title goes to the home page.

#### Scenario: Mobile Navigation
**Given** the Sensei theme is activated
**And** I have published a blog post
**When** I view the blog post on mobile
**Then** the navigation looks similar to the design
**And** I am able to expand and collapse the menu
**And** clicking on a page navigates to that page
**And** clicking on the site title goes to the home page.

**Comment by Luchadores** [comment]
Mobile works well for me in testing. Nicely done 🥳
