### ISSUE TITLE
Update quote block styles

### ISSUE THREAD

**Issue by donnapep** [Automattic/course#8]
Update the quote block's styles to match the [design](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020106%3A1184). Example PRs [here](https://github.com/Automattic/themes/pull/6513) and [here](https://github.com/Automattic/themes/pull/6606).

![Screen Shot 2022-09-30 at 4 51 33 PM](https://user-images.githubusercontent.com/1190420/193354333-54355617-8d22-4b49-946b-bf0ef46c7b6a.jpg)

#### Scenario: Quote Block
**Given** I've added the Quote block to a page
**When** I view the page on the frontend
**Then** the quote block looks similar to the design.

**Comment by donnapep** [comment]
Addressed in #28.

**Comment by Luchadores** [comment]
Tested again. Same as my last comment [here](https://lavagolemnotes.wordpress.com/2022/10/14/call-for-validating/#comment-5).

The quotes look great besides the Cover note from the comment I linked to above.
