### ISSUE TITLE
Update search template

### ISSUE THREAD

**Issue by donnapep** [Automattic/course#9]
Update the search template so that it matches the [design](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020078%3A3812). Example PRs [here](https://github.com/Automattic/themes/pull/6518) and [here](https://github.com/Automattic/themes/pull/6599).

## Desktop
![Screen Shot 2022-09-29 at 6 12 23 PM](https://user-images.githubusercontent.com/1190420/193151428-2145c352-0a0f-4cc6-97b0-9ef514a01e53.jpg)

## Mobile
Note that we don't have mobile designs for this template; however, we can do something similar to the [single post template](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020126%3A4278), where the sidebar content is displayed below the search page content on mobile.

#### Scenario: Search template
**Given** The Sensei theme is activated
**When** I view the search page (e.g. http://one.wordpress.test/?s)
**Then** the page looks similar to the design.

**Comment by Luchadores** [comment]
The Search page looks nice! Well done 🥳 

Let's check the space in-between the page title "Search" and the search bar. And also from the search bar to the content below it. I would also check the spacing in between the main content column and the sidebar.

The screenshot is attached with the values I have from the design on this page.
![image](https://user-images.githubusercontent.com/10038976/197791591-a458d42c-bf1e-4e76-b4b2-a9854a7a22f6.png)

I also wonder what we can do with the default Search bar from the bottom of the page.
Is it possible to make it the same width and aligned it to the left as the main content column?
Or is it possible to make it the entire width of the content? Currently, it sits somewhere in-between.
<img width="564" alt="image" src="https://user-images.githubusercontent.com/10038976/197787436-bcfcb5e8-12db-4365-8677-d18fb92b2c50.png">
