### ISSUE TITLE
Add style variations

### ISSUE THREAD

**Issue by donnapep** [Automattic/course#98]
Add three style variations for the theme that match the [design](https://www.figma.com/file/nf4oV51c1JBxJKXshMe7cd/New-Sensei-Theme?node-id=20020267%3A5521&t=GTk9JK24g9yYZFlA-0):

- Blue
- Dark
- Gold

## Blue
![Screenshot 2022-11-14 at 11 33 48 AM](https://user-images.githubusercontent.com/1190420/201714573-e649120d-9a27-4df0-b114-cb4938d30554.jpg)

## Dark
![Screenshot 2022-11-14 at 11 34 54 AM](https://user-images.githubusercontent.com/1190420/201714722-3429ea82-8bbb-43db-81ee-511144b01108.jpg)

## Gold
![Screenshot 2022-11-14 at 11 35 31 AM](https://user-images.githubusercontent.com/1190420/201714841-d7091554-2719-4ad7-b75b-655b72701007.jpg)

#### Scenario: Switching Style Variations
**Given** I'm viewing the site editor
**And** I open the _Styles_ sidebar
**And** I click the _Browse styles_ link
**When** I select a different theme style
**Then** the theme updates as per the design in both the editor and frontend.

**Comment by LavaGolem** [comment]
There is an issue with buttons, but it's not related to this PR
<img width="985" alt="image" src="https://user-images.githubusercontent.com/7208249/202727553-19877f65-15ec-46e3-b864-b36d241119a0.png">

**Comment by donnapep** [comment]
Yup, see my comment [here](https://github.com/Automattic/course/pull/101#issuecomment-1320065288). The old lesson templates are out-of-scope for the theme project. Only lessons inside Learning Mode will be supported.
